Documen/grails-app/domain/hola/administracion/Registro.groovy
package hola.administracion

class Registro {
    String departamento
    Date fecha
    String destinatario
    String remitente
    String concepto
    Integer year
    Date nueva_fecha

    static constraints= {
        departamento()
        fecha(nullable: true)
        destinatario()
        remitente()
        concepto()
        year(nullable: true)
        nueva_fecha(nullable: true)
    }
    
    static mapping = {
        remitente(type: 'text')
        destinatario(type: 'text')
        concepto(type: 'text')
    }
}

Documen/grails-app/domain/hola/documental/Autor.groovy
package hola.documental

class Autor {
    String nombre
}

Documen/grails-app/domain/hola/documental/Hola.groovy
package hola.documental

import java.util.Date;

class Hola {
    String personaje
    String nacion
    String profesion
    String nacimiento
    String muerte
    String revista
    String numero
    String autor
    String observaciones
    String codigo
    Date fecha

	static hasMany = [paginas: Pagina]
	
    static constraints= {
        numero()
        fecha()
        personaje()
        autor()
        observaciones()
        codigo()
        nacion(nulleable:true)
        nacimiento(nulleable:true)
        profesion(nulleable:true)
        muerte(nulleable:true)
    }
    
    static mapping = {
        autor(type: 'text')
        personaje(type: 'text')
        observaciones(type: 'text')
    }
}

Documen/grails-app/controllers/hola/administracion/RegistroController.groovy
package hola.administracion

class RegistroController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index = {
        redirect(action: "list", params: params)
    }

    def imp= {
        def DBTWRecordSet = new XmlSlurper().parse(new File("${params.file}"))
        def registro, departamento, fecha, destinatario, remitente, concepto, year, nueva_fecha, nfecha, nnueva_fecha, nyear
        DBTWRecordSet.DBTWRecord.each() {r ->
            departamento= r.DEPARTAMENTO?.text()
            fecha= r.FECHA?.text()

            try{
                nfecha=  new Date().parse("dd-MM-yyyy", fecha)
            }
            catch (Exception e){
                try{
                    nfecha=  new Date().parse("ddMMyyyy", fecha)
                }
                catch (Exception e1){
                    try{
                        nfecha=  new Date().parse("dd.MM.yyyy", fecha)
                    }
                    catch (Exception e2){
                        try{
                            nfecha=  new Date().parse("dd/MM/yyyy", fecha)
                        }
                        catch (Exception e3){
                            try{
                                nfecha=  new Date().parse("dd-MM-yy", fecha)
                            }
                            catch (Exception e4){
                                try{
                                    nfecha=  new Date().parse("dd/MM/yy", fecha)
                                }
                                catch (Exception e5){
                                    try{
                                        nfecha=  new Date().parse("dd-MM-yy", fecha)
                                    }
                                    catch (Exception e6){
                                        try{
                                            nfecha=  new Date().parse("dd.MM-yyyy", fecha)
                                        }
                                        catch (Exception e7){
                                            try{
                                                nfecha=  new Date().parse("d de MMMM de yyyy", fecha)
                                            }
                                            catch (Exception e8){
                                                if (fecha!=""){
                                                    println "Error nfecha (-${fecha}-) en ${destinatario}"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            destinatario= r.DESTINATARIO?.text()
            remitente= r.REMITENTE?.text()
            concepto= r.CONCEPTO?.text()
            year= r.YEAR?.text()
            nueva_fecha= r.NUEVAFECHA?.text()
            
            try{
                nnueva_fecha=  new Date().parse("dd/MM/yyyy", nueva_fecha)
            }
            catch (Exception e){
                if (nueva_fecha!=""){
                    println "Error nuevafecha (${nueva_fecha}) en ${destinatario} ${fecha}"
                }
                nnueva_fecha= null
            }
                        
            try{
                nyear= Integer.parseInt(year)
            }
            catch (Exception e){
                if (year!=""){
                    println "Error parseInt (${year}) en ${destinatario}"
                }
                nyear= null
            }

            registro= new Registro(departamento: departamento, fecha: nfecha , destinatario: destinatario, remitente: remitente,
                concepto: concepto, year: nyear, nueva_fecha: nnueva_fecha)
            if (registro.validate()){
                registro.save()
            }
            else{
                registro.errors.allErrors.each {
                    println it
                }
            }
        }
    }

    def search= {
        def results
        if (params.query){            
            def c= Registro.createCriteria()
            results = c {
                or {
                    ilike("remitente", "%${params.query}%")
                    ilike("concepto", "%${params.query}%")
                    ilike("destinatario", "%${params.query}%")
                }
            }
        }

        params.max = Math.min(params.max ? params.int('max') : 25, 100)
        [params:params, query: params.query, registroInstanceList: results , registroInstanceTotal: results?results.size():0]        
    }

    def list = {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [registroInstanceList: Registro.list(params), registroInstanceTotal: Registro.count()]
    }

    def create = {
        def registroInstance = new Registro()
        registroInstance.properties = params
        return [registroInstance: registroInstance]
    }

    def save = {
        def registroInstance = new Registro(params)
        if (registroInstance.save(flush: true)) {
            flash.message = "${message(code: 'default.created.message', args: [message(code: 'registro.label', default: 'Registro'), registroInstance.id])}"
            redirect(action: "show", id: registroInstance.id)
        }
        else {
            render(view: "create", model: [registroInstance: registroInstance])
        }
    }

    def show = {
        def registroInstance = Registro.get(params.id)
        if (!registroInstance) {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'registro.label', default: 'Registro'), params.id])}"
            redirect(action: "list")
        }
        else {
            [registroInstance: registroInstance]
        }
    }

    def edit = {
        def registroInstance = Registro.get(params.id)
        if (!registroInstance) {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'registro.label', default: 'Registro'), params.id])}"
            redirect(action: "list")
        }
        else {
            return [registroInstance: registroInstance]
        }
    }

    def update = {
        def registroInstance = Registro.get(params.id)
        if (registroInstance) {
            if (params.version) {
                def version = params.version.toLong()
                if (registroInstance.version > version) {
                    
                    registroInstance.errors.rejectValue("version", "default.optimistic.locking.failure", [message(code: 'registro.label', default: 'Registro')] as Object[], "Another user has updated this Registro while you were editing")
                    render(view: "edit", model: [registroInstance: registroInstance])
                    return
                }
            }
            registroInstance.properties = params
            if (!registroInstance.hasErrors() && registroInstance.save(flush: true)) {
                flash.message = "${message(code: 'default.updated.message', args: [message(code: 'registro.label', default: 'Registro'), registroInstance.id])}"
                redirect(action: "show", id: registroInstance.id)
            }
            else {
                render(view: "edit", model: [registroInstance: registroInstance])
            }
        }
        else {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'registro.label', default: 'Registro'), params.id])}"
            redirect(action: "list")
        }
    }

    def delete = {
        def registroInstance = Registro.get(params.id)
        if (registroInstance) {
            try {
                registroInstance.delete(flush: true)
                flash.message = "${message(code: 'default.deleted.message', args: [message(code: 'registro.label', default: 'Registro'), params.id])}"
                redirect(action: "list")
            }
            catch (org.springframework.dao.DataIntegrityViolationException e) {
                flash.message = "${message(code: 'default.not.deleted.message', args: [message(code: 'registro.label', default: 'Registro'), params.id])}"
                redirect(action: "show", id: params.id)
            }
        }
        else {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'registro.label', default: 'Registro'), params.id])}"
            redirect(action: "list")
        }
    }
}

Documen/grails-app/controllers/hola/administracion/SeguroController.groovy
package hola.administracion

class SeguroController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index = {
        redirect(action: "list", params: params)
    }

    def imp= {
        def DBTWRecordSet = new XmlSlurper().parse(new File("${params.file}"))
        def seguro, poliza, fecha, vencimiento, clase, lugar, nfecha
        DBTWRecordSet.DBTWRecord.each() {r ->
            poliza= r.POLIZA?.text()
            fecha= r.FECHA?.text()

            try{
                nfecha=  new Date().parse("dd-MM-yyyy", fecha)
            }
            catch (Exception e){
                try{
                    nfecha=  new Date().parse("ddMMyyyy", fecha)
                }
                catch (Exception e1){
                    try{
                        nfecha=  new Date().parse("dd.MM.yyyy", fecha)
                    }
                    catch (Exception e2){
                        try{
                            nfecha=  new Date().parse("dd/MM/yyyy", fecha)
                        }
                        catch (Exception e3){
                            try{
                                nfecha=  new Date().parse("dd-MM-yy", fecha)
                            }
                            catch (Exception e4){
                                try{
                                    nfecha=  new Date().parse("dd/MM/yy", fecha)
                                }
                                catch (Exception e5){
                                    try{
                                        nfecha=  new Date().parse("dd-MM-yy", fecha)
                                    }
                                    catch (Exception e6){
                                        try{
                                            nfecha=  new Date().parse("dd.MM-yyyy", fecha)
                                        }
                                        catch (Exception e7){
                                            try{
                                                nfecha=  new Date().parse("d de MMMM de yyyy", fecha)
                                            }
                                            catch (Exception e8){
                                                if (fecha!=""){
                                                    println "Error nfecha (-${fecha}-) en ${poliza}"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            vencimiento= r.VENCIMIENTO?.text()
            clase= r.CLASE?.text()
            lugar= r.LUGAR?.text()
            
            seguro= new Seguro(poliza: poliza, fecha: nfecha, vencimiento: vencimiento, clase: clase, lugar: lugar)
            if (seguro.validate()){
                seguro.save()
            }
            else{
                seguro.errors.allErrors.each {
                    println it
                }
            }
        }
    }
    
    def search= {
        def results
        if (params.query){            
            def c= Seguro.createCriteria()
            results = c {
                or {
                    ilike("poliza", "%${params.query}%")
                    ilike("vencimiento", "%${params.query}%")
                    ilike("clase", "%${params.query}%")
                    ilike("lugar", "%${params.query}%")
                }
            }
        }
        params.max = Math.min(params.max ? params.int('max') : 25, 100)
        [params:params, query: params.query, seguroInstanceList: results , seguroInstanceTotal: results?results.size():0]        
    }
    
    def list = {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [seguroInstanceList: Seguro.list(params), seguroInstanceTotal: Seguro.count()]
    }

    def create = {
        def seguroInstance = new Seguro()
        seguroInstance.properties = params
        return [seguroInstance: seguroInstance]
    }

    def save = {
        def seguroInstance = new Seguro(params)
        if (seguroInstance.save(flush: true)) {
            flash.message = "${message(code: 'default.created.message', args: [message(code: 'seguro.label', default: 'Seguro'), seguroInstance.id])}"
            redirect(action: "show", id: seguroInstance.id)
        }
        else {
            render(view: "create", model: [seguroInstance: seguroInstance])
        }
    }

    def show = {
        def seguroInstance = Seguro.get(params.id)
        if (!seguroInstance) {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'seguro.label', default: 'Seguro'), params.id])}"
            redirect(action: "list")
        }
        else {
            [seguroInstance: seguroInstance]
        }
    }

    def edit = {
        def seguroInstance = Seguro.get(params.id)
        if (!seguroInstance) {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'seguro.label', default: 'Seguro'), params.id])}"
            redirect(action: "list")
        }
        else {
            return [seguroInstance: seguroInstance]
        }
    }

    def update = {
        def seguroInstance = Seguro.get(params.id)
        if (seguroInstance) {
            if (params.version) {
                def version = params.version.toLong()
                if (seguroInstance.version > version) {
                    
                    seguroInstance.errors.rejectValue("version", "default.optimistic.locking.failure", [message(code: 'seguro.label', default: 'Seguro')] as Object[], "Another user has updated this Seguro while you were editing")
                    render(view: "edit", model: [seguroInstance: seguroInstance])
                    return
                }
            }
            seguroInstance.properties = params
            if (!seguroInstance.hasErrors() && seguroInstance.save(flush: true)) {
                flash.message = "${message(code: 'default.updated.message', args: [message(code: 'seguro.label', default: 'Seguro'), seguroInstance.id])}"
                redirect(action: "show", id: seguroInstance.id)
            }
            else {
                render(view: "edit", model: [seguroInstance: seguroInstance])
            }
        }
        else {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'seguro.label', default: 'Seguro'), params.id])}"
            redirect(action: "list")
        }
    }

    def delete = {
        def seguroInstance = Seguro.get(params.id)
        if (seguroInstance) {
            try {
                seguroInstance.delete(flush: true)
                flash.message = "${message(code: 'default.deleted.message', args: [message(code: 'seguro.label', default: 'Seguro'), params.id])}"
                redirect(action: "list")
            }
            catch (org.springframework.dao.DataIntegrityViolationException e) {
                flash.message = "${message(code: 'default.not.deleted.message', args: [message(code: 'seguro.label', default: 'Seguro'), params.id])}"
                redirect(action: "show", id: params.id)
            }
        }
        else {
            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'seguro.label', default: 'Seguro'), params.id])}"
            redirect(action: "list")
        }
    }
}

Documen/grails-app/views/hola/busca.gsp
<%@page import="java.util.regex.Matcher"%>
<%@ page import="hola.documental.Pagina"%>
<%@ page import="hola.documental.Publicacion"%>
<%@ page import="hola.documental.Ediciones"%>
<g:set var="text" bean="textService" />
<!DOCTYPE html>
<html class="no-js" lang="es">
<head>
<meta name="layout" content="main">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<g:set var="entityName"
	value="${message(code: 'pagina.label', default: 'Pagina')}" />
<title>Búsqueda en Documentación</title>
<script type="text/javascript"
	src="${resource(dir: 'js/vendor', file: 'modernizr.js')}"></script>

<link rel="stylesheet"
	href="${resource(dir: 'css', file: 'foundation.css')}" type="text/css"
	media="screen" />
<link rel="stylesheet"
	href="${resource(dir: 'css', file: 'default.css')}" type="text/css"
	media="screen" />
</head>
<body>


	<g:form method="post" action="busca">
		<div class="row">
			<div class="large-2 medium-2 columns">
				<label>Publicación</label>
				<g:select name="publicacion" from="${Publicacion.list()}"
					value="${params.publicacion}" optionKey="id" optionValue="nombre"
					onchange="${remoteFunction (
                        controller: 'pagina',
                        action: 'range',
                        params: '\'publicacion=\' + this.value',
                        update: 'range'
                )}" />
			</div>
			<div class="large-1 medium-1 columns">
				<label>Edición</label>
				<g:textField name="edicion" size="5" value="${params.edicion}" />
			</div>
			<div class="large-1 medium-1 columns">
				<label>Página</label>
				<g:textField name="pagina" size="5" value="${params.pagina}" />
			</div>
			<div class="large-8 medium-8 columns">



			</div>
		</div>


		<div class="row">
			<div class="large-8 medium-6 columns">
				<label>Consulta</label>
				<g:textField name="q" value="${params.q}" />
			</div>
			<div class="large-2 medium-2 columns">
				<g:actionSubmit action="busca" class="small radius button"
					value="${message(code: 'default.button.search.label', default: 'Buscar')}" />
					</div>
			</div>
		</div>
	</g:form>

	<div class="row">
		<g:if test="${flash.message}">
			<div class="message" role="status">
				${flash.message}
			</div>
		</g:if>
		</div>

		<!-- Documentación -->
	<div class="row">
		<g:if test="${documentoList?.size()>0}">
			${documentoTotal} documentos
					<table>
				<thead>
					<tr>
						<g:sortableColumn property="numero"
							title="${message(code: 'pagina.edicion.label', default: 'Edición')}"
							params="[params: params]" />

						<th><g:message code="contenido" default="Contenido" /></th>
					</tr>
				</thead>
				<tbody>
					<g:each in="${documentoList}" status="i" var="documento">
						<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

							<td><em> 
							
							${documento.revista}
							</em> <br />
							${documento.numero}
							 
							 <g:formatDate format="dd/MM/yyyy"
									date="${documento.fecha}" /></td>

							<td>

								<div id="panel" class="panel"
									title="${documento.autor}" border="false" fit="false">

									<p>${documento.personaje}</p>
									<p>${documento.observaciones}</p>

								</div>
							</td>
						</tr>
					</g:each>
				</tbody>
			</table>


			<div class="pagination">
				<g:paginate total="${documentoTotal}" params="${params}" />
			</div>
		</g:if>

	</div>
	
	<script type="text/javascript"
		src="${resource(dir: 'js/vendor', file: 'jquery.js')}"></script>
	<script type="text/javascript"
		src="${resource(dir: 'js', file: 'foundation.min.js')}"></script>
	<script>
      $(document).foundation();
    </script>

</body>
</html>

Documen/grails-app/views/hola/imp.gsp
<!--
  To change this template, choose Tools | Templates
  and open the template in the editor.
-->

<%@ page contentType="text/html;charset=UTF-8" %>

<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Importación</title>
  </head>
  <body>
    <h1>Importación completa</h1>
  </body>
</html>

Documen/grails-app/views/hola/list.gsp
<%@ page import="hola.documental.Hola" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'hola.label', default: 'Hola')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></span>
            <span class="menuButton"><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></span>
        </div>
        <div class="body">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <div class="list">
                <table>
                    <thead>
                        <tr>
                        
                            <g:sortableColumn property="id" title="${message(code: 'hola.id.label', default: 'Id')}" />
                        
                            <g:sortableColumn property="numero" title="${message(code: 'hola.numero.label', default: 'Numero')}" />
                        
                            <g:sortableColumn property="personaje" title="${message(code: 'hola.personaje.label', default: 'Personaje')}" />
                        
                            <g:sortableColumn property="autor" title="${message(code: 'hola.autor.label', default: 'Autor')}" />
                        
                            <g:sortableColumn property="observaciones" title="${message(code: 'hola.observaciones.label', default: 'Observaciones')}" />
                        
                            <g:sortableColumn property="codigo" title="${message(code: 'hola.codigo.label', default: 'Codigo')}" />
                        
                        </tr>
                    </thead>
                    <tbody>
                    <g:each in="${holaInstanceList}" status="i" var="holaInstance">
                        <tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
                        
                            <td><g:link action="show" id="${holaInstance.id}">${fieldValue(bean: holaInstance, field: "id")}</g:link></td>
                        
                            <td>${fieldValue(bean: holaInstance, field: "numero")}</td>
                        
                            <td>${fieldValue(bean: holaInstance, field: "personaje")}</td>
                        
                            <td>${fieldValue(bean: holaInstance, field: "autor")}</td>
                        
                            <td>${fieldValue(bean: holaInstance, field: "observaciones")}</td>
                        
                            <td>${fieldValue(bean: holaInstance, field: "codigo")}</td>
                        
                        </tr>
                    </g:each>
                    </tbody>
                </table>
            </div>
            <div class="paginateButtons">
                <g:paginate total="${holaInstanceTotal}" />
            </div>
        </div>
    </body>
</html>

Documen/grails-app/views/hola/search.gsp
<%@ page import="hola.documental.Hola" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'hola.label', default: 'Hola')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></span>
            <span class="menuButton"><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></span>
        </div>
        <div class="body">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            
            <g:form method="post" >
              <g:textField name="query" value="${query}" />
              <span class="button"><g:actionSubmit class="search" action="search" value="${message(code: 'default.button.search.label', default: 'Search')}"/></span>
            </g:form>
            
            <g:if test="${holaInstanceTotal>0}">
            <h3>${holaInstanceTotal} resultados</h3>
            </g:if>
            
            <div class="list">
                <table>
                    <thead>
                        <tr>
                        
                            <g:sortableColumn property="id" title="${message(code: 'hola.id.label', default: 'Id')}" />
                        
                            <g:sortableColumn property="numero" title="${message(code: 'hola.numero.label', default: 'Número')}" />
                        
                            <g:sortableColumn property="personaje" title="${message(code: 'hola.personaje.label', default: 'Personaje')}" />
                        
                            <g:sortableColumn property="autor" title="${message(code: 'hola.autor.label', default: 'Autor')}" />
                        
                            <g:sortableColumn property="observaciones" title="${message(code: 'hola.observaciones.label', default: 'Observaciones')}" />
                        
                            <g:sortableColumn property="codigo" title="${message(code: 'hola.codigo.label', default: 'Codigo')}" />
                        
                        </tr>
                    </thead>
                    <tbody>
                    <g:each in="${holaInstanceList}" status="i" var="holaInstance">
                        <tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
                        
                            <td><g:link action="show" id="${holaInstance.id}">${fieldValue(bean: holaInstance, field: "id")}</g:link></td>
                        
                            <td>${fieldValue(bean: holaInstance, field: "numero")}</td>
                        
                            <td>${fieldValue(bean: holaInstance, field: "personaje")}</td>
                        
                            <td>${fieldValue(bean: holaInstance, field: "autor")}</td>
                        
                            <td>${fieldValue(bean: holaInstance, field: "observaciones")}</td>
                        
                            <td>${fieldValue(bean: holaInstance, field: "codigo")}</td>
                        
                        </tr>
                    </g:each>
                    </tbody>
                </table>
            </div>
            <div class="paginateButtons">
                <g:paginate total="${holaInstanceTotal}" />
            </div>
        </div>
    </body>
</html>