Documen/grails-app/domain/hola/documental/Ediciones.groovy
package hola.documental

import java.util.Date;

class Ediciones implements Comparable, Serializable{
  Publicacion publicacion
  Integer numero
  String imagen
  Date fechaPortada
  String nombre
  
  Date dateCreated
  Date lastUpdated
  
    String toString(){
        return String.format('%d : %td /%<tm /%<tY', numero, fechaPortada)
    }

    int compareTo(Object e){
        return (e instanceof Ediciones) ? e.fechaPortada - fechaPortada : 0
    }
}

Documen/grails-app/controllers/hola/documental/EdicionesController.groovy
package hola.documental

import org.springframework.dao.DataIntegrityViolationException

class EdicionesController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        [edicionesInstanceList: Ediciones.list(params), edicionesInstanceTotal: Ediciones.count()]
    }

    def create() {
        [edicionesInstance: new Ediciones(params)]
    }

    def save() {
        def edicionesInstance = new Ediciones(params)
        if (!edicionesInstance.save(flush: true)) {
            render(view: "create", model: [edicionesInstance: edicionesInstance])
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'ediciones.label', default: 'Ediciones'), edicionesInstance.id])
        redirect(action: "show", id: edicionesInstance.id)
    }

    def show(Long id) {
        def edicionesInstance = Ediciones.get(id)
        if (!edicionesInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'ediciones.label', default: 'Ediciones'), id])
            redirect(action: "list")
            return
        }

        [edicionesInstance: edicionesInstance]
    }

    def edit(Long id) {
        def edicionesInstance = Ediciones.get(id)
        if (!edicionesInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'ediciones.label', default: 'Ediciones'), id])
            redirect(action: "list")
            return
        }

        [edicionesInstance: edicionesInstance]
    }

    def update(Long id, Long version) {
        def edicionesInstance = Ediciones.get(id)
        if (!edicionesInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'ediciones.label', default: 'Ediciones'), id])
            redirect(action: "list")
            return
        }

        if (version != null) {
            if (edicionesInstance.version > version) {
                edicionesInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'ediciones.label', default: 'Ediciones')] as Object[],
                          "Another user has updated this Ediciones while you were editing")
                render(view: "edit", model: [edicionesInstance: edicionesInstance])
                return
            }
        }

        edicionesInstance.properties = params

        if (!edicionesInstance.save(flush: true)) {
            render(view: "edit", model: [edicionesInstance: edicionesInstance])
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'ediciones.label', default: 'Ediciones'), edicionesInstance.id])
        redirect(action: "show", id: edicionesInstance.id)
    }

    def delete(Long id) {
        def edicionesInstance = Ediciones.get(id)
        if (!edicionesInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'ediciones.label', default: 'Ediciones'), id])
            redirect(action: "list")
            return
        }

        try {
            edicionesInstance.delete(flush: true)
            flash.message = message(code: 'default.deleted.message', args: [message(code: 'ediciones.label', default: 'Ediciones'), id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'ediciones.label', default: 'Ediciones'), id])
            redirect(action: "show", id: id)
        }
    }
}

Documen/grails-app/views/ediciones/_form.gsp
<%@ page import="hola.documental.Ediciones" %>



<div class="fieldcontain ${hasErrors(bean: edicionesInstance, field: 'fechaPortada', 'error')} required">
	<label for="fechaPortada">
		<g:message code="ediciones.fechaPortada.label" default="Fecha Portada" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="fechaPortada" precision="day"  value="${edicionesInstance?.fechaPortada}"  />
</div>

<div class="fieldcontain ${hasErrors(bean: edicionesInstance, field: 'imagen', 'error')} ">
	<label for="imagen">
		<g:message code="ediciones.imagen.label" default="Imagen" />
		
	</label>
	<g:textField name="imagen" value="${edicionesInstance?.imagen}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: edicionesInstance, field: 'nombre', 'error')} ">
	<label for="nombre">
		<g:message code="ediciones.nombre.label" default="Nombre" />
		
	</label>
	<g:textField name="nombre" value="${edicionesInstance?.nombre}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: edicionesInstance, field: 'numero', 'error')} required">
	<label for="numero">
		<g:message code="ediciones.numero.label" default="Numero" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="numero" type="number" value="${edicionesInstance.numero}" required=""/>
</div>

<div class="fieldcontain ${hasErrors(bean: edicionesInstance, field: 'publicacion', 'error')} required">
	<label for="publicacion">
		<g:message code="ediciones.publicacion.label" default="Publicacion" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="publicacion" name="publicacion.id" from="${hola.documental.Publicacion.list()}" optionKey="id" required="" value="${edicionesInstance?.publicacion?.id}" class="many-to-one"/>
</div>

Documen/grails-app/views/ediciones/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'ediciones.label', default: 'Ediciones')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-ediciones" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-ediciones" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${edicionesInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${edicionesInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:edicionesInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Documen/grails-app/views/ediciones/edit.gsp
<%@ page import="hola.documental.Ediciones" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'ediciones.label', default: 'Ediciones')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-ediciones" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-ediciones" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${edicionesInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${edicionesInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:edicionesInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${edicionesInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Documen/grails-app/views/ediciones/index.gsp
<%@ page import="hola.documental.Ediciones" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'ediciones.label', default: 'Ediciones')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-ediciones" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-ediciones" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="fechaPortada" title="${message(code: 'ediciones.fechaPortada.label', default: 'Fecha Portada')}" />
					
						<g:sortableColumn property="imagen" title="${message(code: 'ediciones.imagen.label', default: 'Imagen')}" />
					
						<g:sortableColumn property="nombre" title="${message(code: 'ediciones.nombre.label', default: 'Nombre')}" />
					
						<g:sortableColumn property="numero" title="${message(code: 'ediciones.numero.label', default: 'Numero')}" />
					
						<th><g:message code="ediciones.publicacion.label" default="Publicacion" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${edicionesInstanceList}" status="i" var="edicionesInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${edicionesInstance.id}">${fieldValue(bean: edicionesInstance, field: "fechaPortada")}</g:link></td>
					
						<td>${fieldValue(bean: edicionesInstance, field: "imagen")}</td>
					
						<td>${fieldValue(bean: edicionesInstance, field: "nombre")}</td>
					
						<td>${fieldValue(bean: edicionesInstance, field: "numero")}</td>
					
						<td>${fieldValue(bean: edicionesInstance, field: "publicacion")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${edicionesInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

Documen/grails-app/views/ediciones/list.gsp
<%@ page import="hola.documental.Ediciones" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'ediciones.label', default: 'Ediciones')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-ediciones" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-ediciones" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<g:sortableColumn property="fechaPortada" title="${message(code: 'ediciones.fechaPortada.label', default: 'Fecha Portada')}" />
					
						<g:sortableColumn property="imagen" title="${message(code: 'ediciones.imagen.label', default: 'Imagen')}" />
					
						<g:sortableColumn property="nombre" title="${message(code: 'ediciones.nombre.label', default: 'Nombre')}" />
					
						<g:sortableColumn property="numero" title="${message(code: 'ediciones.numero.label', default: 'Numero')}" />
					
						<th><g:message code="ediciones.publicacion.label" default="Publicacion" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${edicionesInstanceList}" status="i" var="edicionesInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${edicionesInstance.id}">${fieldValue(bean: edicionesInstance, field: "fechaPortada")}</g:link></td>
					
						<td>${fieldValue(bean: edicionesInstance, field: "imagen")}</td>
					
						<td>${fieldValue(bean: edicionesInstance, field: "nombre")}</td>
					
						<td>${fieldValue(bean: edicionesInstance, field: "numero")}</td>
					
						<td>${fieldValue(bean: edicionesInstance, field: "publicacion")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${edicionesInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

Documen/grails-app/views/ediciones/show.gsp
<%@ page import="hola.documental.Ediciones" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main"/>
		<g:set var="entityName" value="${message(code: 'ediciones.label', default: 'Ediciones')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-ediciones" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-ediciones" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list ediciones">
			
				<g:if test="${edicionesInstance?.fechaPortada}">
				<li class="fieldcontain">
					<span id="fechaPortada-label" class="property-label"><g:message code="ediciones.fechaPortada.label" default="Fecha Portada" /></span>
					
						<span class="property-value" aria-labelledby="fechaPortada-label"><g:formatDate date="${edicionesInstance?.fechaPortada}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${edicionesInstance?.imagen}">
				<li class="fieldcontain">
					<span id="imagen-label" class="property-label"><g:message code="ediciones.imagen.label" default="Imagen" /></span>
					
						<span class="property-value" aria-labelledby="imagen-label"><g:fieldValue bean="${edicionesInstance}" field="imagen"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${edicionesInstance?.nombre}">
				<li class="fieldcontain">
					<span id="nombre-label" class="property-label"><g:message code="ediciones.nombre.label" default="Nombre" /></span>
					
						<span class="property-value" aria-labelledby="nombre-label"><g:fieldValue bean="${edicionesInstance}" field="nombre"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${edicionesInstance?.numero}">
				<li class="fieldcontain">
					<span id="numero-label" class="property-label"><g:message code="ediciones.numero.label" default="Numero" /></span>
					
						<span class="property-value" aria-labelledby="numero-label"><g:fieldValue bean="${edicionesInstance}" field="numero"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${edicionesInstance?.publicacion}">
				<li class="fieldcontain">
					<span id="publicacion-label" class="property-label"><g:message code="ediciones.publicacion.label" default="Publicacion" /></span>
					
						<span class="property-value" aria-labelledby="publicacion-label"><g:link controller="publicacion" action="show" id="${edicionesInstance?.publicacion?.id}">${edicionesInstance?.publicacion?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:edicionesInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${edicionesInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>